language: cpp
compiler: mpic++
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sudo apt update
  - apt search libpng
  - sudo apt install -y tree openssh-client openssh-server openmpi-bin openmpi-common libopenmpi-dev cppcheck imagemagick freeglut3 freeglut3-dev libtiff-dev libpng-dev libjpeg-dev
script: 
  - make VERIFY=true
  - bin/another_path_tracer
  - make clean
  - make
before_script: 
after_script:  make clean
before_script: