language: cpp
compiler: mpic++
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sudo apt update
  - sudo apt install -y tree openssh-client openssh-server openmpi-bin openmpi-common libopenmpi1.6 libopenmpi-dev libopenmpi1.6-dbg cppcheck zlib1g zlib1g-dbg zlib1g-dev libpng-dev freetype2-demos
  - git clone https://github.com/pngwriter/pngwriter.git
  - mkdir -p pngwriter-build
  - cd pngwriter-build
  - cmake ../pngwriter
  - make -j
  - sudo make install -y
script: 
  - make VERIFY=true
  - ./bin/another_path_tracer
  - make clean
  - make
before_script: 
after_script:  make clean
before_script: