name: build-and-test
on: [push]
jobs:
  setup-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -la
      - run: mkdir build
      - run: cd build
      - run: pwd
      - run: ls -la
      - run: cmake .. -DCMAKE_BUILD_TYPE=Release
        working-directory: ${{env.working-directory}}/build
      - run: cmake --build .
        working-directory: ${{env.working-directory}}/build
      - run: ctest
        working-directory: ${{env.working-directory}}/build
