name: build-and-test
on: [push]
jobs:
  Ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies (Ubuntu)
        run: sudo apt install freeglut3-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Creating build directory (Ubuntu)
        run: mkdir build
      - name: Running CMake (Ubuntu)
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
        working-directory: ${{ github.workspace }}/build
      - name: Build (Ubuntu)
        run: cmake --build .
        working-directory: ${{ github.workspace }}/build
      - name: Tests (Ubuntu)
        run: ctest
        working-directory: ${{ github.workspace }}/build
  Windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare vcpkg (Windows)
        uses: lukka/run-vcpkg@v6
        id: runvcpkg
        with:
          vcpkgArguments: zlib:x64-windows libpng:x64-windows libjpeg-turbo:x64-windows tiff:x64-windows freeglut:x64-windows
          vcpkgDirectory: ${{ runner.workspace }}/another_path_tracer/vcpkg/
          vcpkgGitCommitId: ec6fe06e8da05a8157dc8581fa96b36b571c1bd5
          vcpkgTriplet: x64-windows
      - name: Running CMake (Windows)
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}\another_path_tracer\vcpkg\scripts\buildsystems\vcpkg.cmake
      - name: Build (Windows)
        run: |
          cd build
          cmake --build .
      - name: Tests (Windows)
        run: |
          cd build
          ctest
  macOS:
    name: build-macos
    runs-on: macos-latest
    steps:
      - name: Installing dependencies (macOS)
        run: brew install libomp
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running CMake (macOS)
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
      - name: Build (macOS)
        run: |
          cd build
          cmake --build .
      - name: Tests (macOS)
        run: |
          cd build
          ctest
