name: build-and-test
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo AAA
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: mkdir build
      - run: cd build
      - run: cmake .. -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build .
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ctest
