name: build-and-test
on: [push]
jobs:
  Ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        run: sudo apt install freeglut3-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running CMake (Ubuntu)
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
      - name: Build (Ubuntu)
        run: |
          cd build
          cmake --build .
      - name: Tests (Ubuntu)
        run: |
          cd build
          ctest
