name: build-and-test
on: [push]
jobs:
  Ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies (Ubuntu)
        run: sudo apt install freeglut3-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running CMake (Ubuntu)
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
      - name: Build (Ubuntu)
        run: |
          cd build
          cmake --build .
      - name: Tests (Ubuntu)
        run: |
          cd build
          ctest
  Windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - name: Installing vcpkg (Windows)
        # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
      - name: Installing dependencies (Windows)
        run: |
        $VCPKG_ROOT/vcpkg install zlib:linux-x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running CMake (Windows)
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
      - name: Build (Windows)
        run: |
          cd build
          cmake --build .
      - name: Tests (Windows)
        run: |
          cd build
          ctest
